name: KaiHeiLa.Net Archive Deploy

on:
  push:
    branches: [ kaiheila-net-archive ]
  pull_request:
    branches: [ kaiheila-net-archive ]

jobs:
  deploy:
    
    # Build Solution
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore Dependencies
      run: dotnet restore src

    - name: Build
      run: dotnet build src --no-restore

    # Packages

    - name: Generate Packages
      run: dotnet pack src --configuration Release --output packages
      
    - name: Push Packages to NuGet
      run: dotnet nuget push ./packages/*.nupkg -k ${NUGET_TOKEN} -s https://api.nuget.org/v3/index.json --skip-duplicate
      env:
        NUGET_TOKEN: ${{secrets.ARCHIVE_NUGET_API_KEY}}

    - name: Push Packages to Github
      run: dotnet nuget push ./packages/*.nupkg -k ${GITHUB_TOKEN} -s https://nuget.pkg.github.com/gehongyan/index.json --skip-duplicate
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
