name: KaiHeiLa.Net Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    - name: Restore Dependencies
      run: dotnet restore src
      
    - name: Build
      run: dotnet build src --no-restore
#    - name: Test
#      run: dotnet test src --no-build --verbosity normal
    
    - name: Publish Core to NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: src/KaiHeiLa.Net.Core/KaiHeiLa.Net.Core.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        
    - name: Publish Rest NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: src/KaiHeiLa.Net.Rest/KaiHeiLa.Net.Rest.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        
    - name: Publish WebSocket to NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: src/KaiHeiLa.Net.WebSocket/KaiHeiLa.Net.WebSocket.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
     
    - name: Generate Packages for Github
      run: dotnet pack src --configuration Release --output packages
      
    - name: Publish Packages to Github
      run: dotnet nuget push ./packages/*.nupkg -k ${GITHUB_TOKEN} -s https://nuget.pkg.github.com/gehongyan/index.json --skip-duplicate
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}